* Message d'invitation
** Message groupé
Coucou, fidèle à moi-même j'écris ce message bien trop tard : je soutiens ma thèse le 11 octobre, au labo à Lille (40 avenue Halley, 59650 Villeneuve d'Ascq https://www.openstreetmap.org/way/79508998).

La soutenance en elle-même est à 15h et dure environ 3h (45min de présentation, puis environ 1h30-2h de questions, 30min de délibération du jury, puis quelques minutes de discours émouvant). Il y aura ensuite un pot convivial au labo de 18h à 20h (heure de fermeture du labo), avec du manger et du boire local ! Puis la soirée continuera à Wazemmes, a priori au bar bu place Casquette à partir de 21h (à confirmer).

Si vous voulez venir à la soutenance ou au pot, il faut bien me le dire car je dois donner une liste des personnes qui viendront, et il faudra présenter une carte d'identité à l'accueil en arrivant. (On s'entend on peut toujours s'arranger sur le moment mais c'est plus simple comme ça.) Pour venir au bar il y a pas besoin de prévenir, et si vous avez un doute sur l'endroit où nous serons, vous pouvez toujours m'appeler au 06 59 80 73 42.

** Message solo
Coucou, fidèle à moi-même j'écris ce message bien trop tard : je soutiens ma thèse le 11 octobre, au labo à Lille (40 avenue Halley, 59650 Villeneuve d'Ascq https://www.openstreetmap.org/way/79508998).

La soutenance en elle-même est à 15h et dure environ 3h (45min de présentation, puis environ 1h30-2h de questions, 30min de délibération du jury, puis quelques minutes de discours émouvant). Il y aura ensuite un pot convivial au labo de 18h à 20h (heure de fermeture du labo), avec du manger et du boire local ! Puis la soirée continuera à Wazemmes, a priori au bar bu place Casquette à partir de 21h (à confirmer).

Dis moi si tu penses venir à la soutenance ou au pot, car je dois donner une liste des personnes qui seront là, et il faudra présenter une carte d'identité à l'accueil en arrivant. (On s'entend on peut toujours s'arranger sur le moment mais c'est plus simple comme ça.) Pour venir au bar il y a pas besoin de prévenir, et si tu as un doute sur l'endroit où nous serons, tu peux toujours m'appeler au 06 59 80 73 42.

* A inviter
- Clément
- Aline
- Melvin
- Céline
- Céline
- Yanis
- Emil

* Invited
(B) = seulement au bar
** From Lille
- Baptiste
- Margaux
- Quentin
- Tanguy
- Amélie
- Loïc
- Amélie
- Lisa
- Paola
- David
- Evan
** Outside Lille
- Cesar
* Present
** From Lille
- Loïc
- Gaspard (B)
- Adnan (B)
** Outside Lille
- Yann
- Aria
- Hippolyte
- Sabine
- Batiste (tentatively, maybe will take a hotel)

* Declined
- Arsène
- Nico?
